FROM alpine:latest
RUN apk add --no-cache ca-certificates libc6-compat
COPY bin/sentry-warden /usr/local/bin/sentry-warden
RUN chmod +x /usr/local/bin/sentry-warden
EXPOSE 8000
ENTRYPOINT ["/usr/local/bin/sentry-warden"]

