apiVersion: v1
kind: ServiceAccount
metadata:
  name: spire-server
  namespace: spire
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spire-agent
  namespace: spire
---
apiVersion: v1
kind: Service
metadata:
  name: spire-server
  namespace: spire
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: spire-server
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spire-server
  namespace: spire
spec:
  selector:
    matchLabels:
      app: spire-server
  serviceName: spire-server
  replicas: 1
  template:
    metadata:
      labels:
        app: spire-server
    spec:
      serviceAccountName: spire-server
      containers:
      - name: spire-server
        image: localhost:5000/spire-server:clean
        imagePullPolicy: IfNotPresent
        command: ["/opt/spire/bin/spire-server"]
        args: ["run", "-config", "/run/spire/config/server.conf"]
        volumeMounts:
          - name: spire-config
            mountPath: /run/spire/config
          - name: spire-data
            mountPath: /run/spire/data
          - name: spire-bundle
            mountPath: /run/spire/bundle
      volumes:
        - name: spire-config
          configMap:
            name: spire-server-forced
        - name: spire-data
          emptyDir: {}
        - name: spire-bundle
          hostPath:
            path: /run/spire/bundle
            type: DirectoryOrCreate
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: spire-agent
  namespace: spire
spec:
  selector:
    matchLabels:
      app: spire-agent
  template:
    metadata:
      labels:
        app: spire-agent
    spec:
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: spire-agent
      initContainers:
        - name: wait-for-bundle
          image: busybox:1.28
          command: ['sh', '-c', 'until [ -f /run/spire/bundle/bundle.crt ]; do echo waiting for bundle; sleep 2; done;']
          volumeMounts:
            - name: spire-bundle
              mountPath: /run/spire/bundle
      containers:
        - name: spire-agent
          image: localhost:5000/spire-server:clean
          imagePullPolicy: IfNotPresent
          command: ["/opt/spire/bin/spire-agent"]
          args: ["run", "-config", "/run/spire/config/agent.conf"]
          securityContext:
            privileged: true
          volumeMounts:
            - name: spire-config
              mountPath: /run/spire/config
            - name: spire-bundle
              mountPath: /run/spire/bundle
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
            - name: spire-agent-token
              mountPath: /var/run/secrets/tokens
              readOnly: true
      volumes:
        - name: spire-config
          configMap:
            name: spire-agent
        - name: spire-bundle
          hostPath:
            path: /run/spire/bundle
            type: DirectoryOrCreate
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: DirectoryOrCreate
        - name: spire-agent-token
          projected:
            sources:
              - serviceAccountToken:
                  path: spire-agent
                  expirationSeconds: 7200
                  audience: spire-server
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spire-server-trust-role
rules:
  - apiGroups: ["authentication.k8s.io"]
    resources: ["tokenreviews"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spire-server-trust-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spire-server-trust-role
subjects:
  - kind: ServiceAccount
    name: spire-server
    namespace: spire

