apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spire-server
  namespace: spire
spec:
  selector:
    matchLabels:
      app: spire-server
  serviceName: spire-server
  replicas: 1
  template:
    metadata:
      labels:
        app: spire-server
    spec:
      # Ensure the pod has permission to write to volumes
      securityContext:
        fsGroup: 1000
      containers:
      - name: spire-server
        image: vecta/spire-server:clean
        imagePullPolicy: IfNotPresent
        command: ["/opt/spire/bin/spire-server"]
        args:
          - "run"
          - "-config"
          - "/run/spire/config/server.conf"
        ports:
          - containerPort: 8081
        volumeMounts:
          - name: spire-config
            mountPath: /run/spire/config
            readOnly: true
          - name: spire-data
            mountPath: /run/spire/data
      volumes:
        - name: spire-config
          configMap:
            name: spire-server-forced
        - name: spire-data
          emptyDir: {}

