apiVersion: v1
kind: ConfigMap
metadata:
  name: spire-server-forced
  namespace: spire
data:
  server.conf: |
    server {
      bind_address = "0.0.0.0"
      bind_port = "8081"
      trust_domain = "vecta.io"
      data_dir = "/run/spire/data"
      log_level = "DEBUG"
      ca_key_type = "rsa-2048"
      ca_subject = {
        country = ["US"], organization = ["Vecta"], common_name = "vecta.io",
      }
    }
    plugins {
      DataStore "sql" {
        plugin_data {
          database_type = "sqlite3"
          connection_string = "/run/spire/data/spire.db"
        }
      }
      NodeAttestor "k8s_psat" {
        plugin_data {
          clusters = { "default" = { service_account_allow_list = ["spire:spire-agent"] } }
        }
      }
      KeyManager "memory" {}
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spire-agent
  namespace: spire
data:
  agent.conf: |
    agent {
      data_dir = "/run/spire/bundle"
      log_level = "DEBUG"
      server_address = "spire-server"
      server_port = "8081"
      socket_path = "/run/spire/sockets/agent.sock"
      trust_bundle_path = "/run/spire/bundle/bundle.crt"
      trust_domain = "vecta.io"
    }
    plugins {
      NodeAttestor "k8s_psat" { plugin_data { cluster = "default" } }
      KeyManager "memory" {}
      WorkloadAttestor "k8s" { plugin_data { skip_kubelet_verification = true } }
    }

